=== pcson/Project---XML/CourseModel-Initial.dtd
<?xml encoding="UTF-8"?>

<!ELEMENT Courses (Course*)>
<!ATTLIST Courses
  xmlns CDATA #FIXED ''>

<!ELEMENT Course (UID,CourseCCN,CourseSemester,CourseCode,CourseShortCode,
                  CourseDepartmentalCode,CourseTitle,
                  CourseAlternariveTitles?,CourseDescriptions,Department,Units,
                  CourseFormat,CourseStartDate,CourseEndDate,Sections,
                  Instructors,Readings?,Grading,
                  Milestones?,ClassPerformance?,PreviousCourseCCN?,
                  FinalExamGroup?,Restrictions,Notes?,Prerequisites?,
                  EquivilantCourses?,CourseEntryStatus?,Enrolment?,Fulfilments?)>

<!ELEMENT UID (#PCDATA)>
<!ELEMENT CourseCCN (#PCDATA)>
<!ELEMENT CourseSemester (#PCDATA) >
<!ELEMENT CourseCode (#PCDATA)>
<!ELEMENT CourseShortCode (#PCDATA)>
<!ELEMENT CourseDepartmentalCode (#PCDATA)>
<!ELEMENT CourseTitle (#PCDATA)>
<!ELEMENT CourseAlternariveTitles (AlternativeTitle*)>
<!ELEMENT CourseDescriptions (GeneralCatalog?,DepartmentDescription?)>
<!ELEMENT CourseFormat (CourseFormatOption+)>
<!ELEMENT CourseStartDate (#PCDATA)>
<!ELEMENT CourseEndDate (#PCDATA)>
<!ELEMENT Sections (Section)+>
<!ELEMENT Instructors (Instructor+)>
<!ELEMENT Readings (ReadingEntry)*>
<!ELEMENT Units (#PCDATA)>
<!ELEMENT Grading (CreditOptions,GradingOptions,GradingBreakdown?)>
<!ELEMENT Milestones (Milestone)*>
<!ELEMENT ClassPerformance (Grades,InstructorEvaluation)>
<!ELEMENT PreviousCourseCCN (#PCDATA)>
<!ELEMENT FinalExamGroup (#PCDATA)>
<!ELEMENT Restrictions (Restriction*)>
<!ELEMENT Notes (#PCDATA)>
<!ELEMENT Prerequisites (Prerequisite*)>
<!ELEMENT Prerequisite (PrerequisiteCCN?, PrerequisiteCourseCode?, PrerequisiteNotes?)>
<!ELEMENT EquivilantCourses (EquivalentCourseCCN*)>
<!ELEMENT CourseEntryStatus (CreatedOn,CreatedBy,ModifiedOn,ModifiedBy)>
<!ELEMENT Enrolment (EnrolmentStatus*)>
<!ELEMENT Fulfilments (Fulfilment*)>
<!ELEMENT AlternativeTitle (#PCDATA)>
<!ELEMENT GeneralCatalog (#PCDATA)>
<!ELEMENT DepartmentDescription (#PCDATA)>
<!ELEMENT CourseFormatOption (CourseHours,CourseFormatType,
                             CourseFormatFrequency)>

<!ELEMENT Section (SectionTitle,SectionCode,SectionShortCode, SectionCCN,SectionType,
                   SectionInstructor,SectionSchedule)>
<!ELEMENT Instructor (InstructorName, InstructorType, InstructorEmail?, InstructorLink*)>
<!ELEMENT InstructorEmail (#PCDATA)>
<!ELEMENT InstructorLink (#PCDATA) >
<!ELEMENT ReadingEntry (ReadingTitle, ReadingEdition?, ReadingAuthors?,ReadingType?, ReadingISBN?, ReadingFormats?
                        ,ReadingPublisher?,ReadingLink?,ReadingAvailableInCampusBookstore?,ReadingRequirementCategory, ReadingEntryNotes?)>

<!ELEMENT CreditOptions (#PCDATA)><!--  Rigid|Flexible -->
<!ELEMENT GradingOptions (GradingOption+)> <!-- Multi value from Graded|Passfail|Auditable-->
<!ELEMENT GradingBreakdown (GradingElement+)>

<!ELEMENT Milestone (MilestoneTitle,MilestoneType,MilestoneDueDate,
                     MilestoneDueTime,MilestoneDueLocation)>
<!ELEMENT Grades (StudentGrades,ClassAverage)>
<!ELEMENT InstructorEvaluation (#PCDATA)>
<!ELEMENT Restriction (#PCDATA)>
<!ELEMENT PrerequisiteCCN (#PCDATA)>          <!-- links to the most recent instance of a prerequisite courses-->
<!ELEMENT PrerequisiteCourseCode (#PCDATA) >
<!ELEMENT PrerequisiteNotes (#PCDATA) >
<!ELEMENT EquivalentCourseCCN  (#PCDATA)>
<!ELEMENT CreatedOn (#PCDATA)>
<!ELEMENT CreatedBy (#PCDATA)>
<!ELEMENT ModifiedOn (#PCDATA)>
<!ELEMENT ModifiedBy (#PCDATA)>
<!ELEMENT EnrolmentStatus (EnrolmentUpdate)>
<!ELEMENT Fulfilment (Degree,Department,Requirement,FullfillmentType)>
<!ELEMENT CourseHours (#PCDATA)>
<!ELEMENT CourseFormatType (#PCDATA)>
<!ELEMENT CourseFormatFrequency (#PCDATA)>
<!ELEMENT SectionTitle (#PCDATA)>
<!ELEMENT SectionCode (#PCDATA)>
<!ELEMENT SectionShortCode (#PCDATA)>
<!ELEMENT SectionCCN (#PCDATA)>
<!ELEMENT SectionType (#PCDATA)>
<!ELEMENT SectionInstructor (#PCDATA)>
<!ELEMENT SectionSchedule (SectionScheduleEntry)+>
<!ELEMENT InstructorName (#PCDATA)>
<!ELEMENT InstructorType (#PCDATA)><!--! Professor, Lecturer, Guest Lecturer, Guest Spaeker  -->

<!ELEMENT ReadingTitle (#PCDATA)>
<!ELEMENT ReadingEdition (#PCDATA)>
<!ELEMENT ReadingAuthors (ReadingAuthorName+)>
<!ELEMENT ReadingISBN (#PCDATA) >
<!ELEMENT ReadingType (#PCDATA)>
<!ELEMENT ReadingFormats (ReadingFormat*)>
<!ELEMENT ReadingPublisher (#PCDATA)>
<!ELEMENT ReadingFormat (#PCDATA)>
<!ELEMENT ReadingLink (#PCDATA)>
<!ELEMENT ReadingRequirementCategory (#PCDATA)> <!-- Required, Recommended-->
<!ELEMENT ReadingAvailableInCampusBookstore (#PCDATA) >
<!ELEMENT ReadingEntryNotes (#PCDATA) >
<!ELEMENT GradingOption (#PCDATA)>
<!ELEMENT GradingElement (GradingElementTitle,GradingElementType,
                          GradingElementWeight)>
<!ELEMENT MilestoneTitle (#PCDATA)>
<!ELEMENT MilestoneType (#PCDATA)>
<!ELEMENT MilestoneDueDate (#PCDATA)>
<!ELEMENT MilestoneDueTime (#PCDATA)>
<!ELEMENT MilestoneDueLocation (#PCDATA)>
<!ELEMENT StudentGrades (StudentGrade)>
<!ELEMENT ClassAverage (#PCDATA)>
<!ELEMENT EnrolmentUpdate (EnrolmentUpdatedOn,Limit,Enrolled,Waitlist,
                           AvailableSeats)>
<!ELEMENT Degree (#PCDATA)>
<!ELEMENT Requirement (#PCDATA)>
<!ELEMENT FullfillmentType (#PCDATA)>
<!ELEMENT SectionScheduleEntry (ScheduledTime,ScheduledLocation)>
<!ELEMENT ReadingAuthorName (#PCDATA)>
<!ELEMENT GradingElementTitle (#PCDATA)>
<!ELEMENT GradingElementType (#PCDATA)> <!-- Assignment|Projects|Class Participation|Mid Term|Final Examl -->
<!ELEMENT GradingElementWeight (#PCDATA)>
<!ELEMENT StudentGrade (#PCDATA)>
<!ELEMENT EnrolmentUpdatedOn (#PCDATA)>
<!ELEMENT Limit (#PCDATA)>
<!ELEMENT Enrolled (#PCDATA)>
<!ELEMENT Waitlist (#PCDATA)>
<!ELEMENT AvailableSeats (#PCDATA)>
<!ELEMENT ScheduledTime (Day+,StartTime,EndTime,Frequency)>
<!ELEMENT ScheduledLocation (Building,Room)>
<!ELEMENT Day (#PCDATA)>
<!ELEMENT StartTime (#PCDATA)>
<!ELEMENT EndTime (#PCDATA)>
<!ELEMENT Frequency (#PCDATA)>
<!ELEMENT Building (#PCDATA)>
<!ELEMENT Room (#PCDATA)>
<!ELEMENT Department (#PCDATA)>

=== pcson/Project---XML/CourseModel-Initial.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Courses SYSTEM "CourseModel-Initial.dtd">
<Courses>
    <Course>
        <UID>1</UID>
        <CourseCCN>41613</CourseCCN>
        <CourseSemester>Fall 2013</CourseSemester>
        <CourseCode>INFORMATION 242</CourseCode>
        <CourseShortCode>INFO 242</CourseShortCode>
        <CourseDepartmentalCode>i242</CourseDepartmentalCode>
        <CourseTitle>XML Foundations</CourseTitle>
        <CourseDescriptions>
            <GeneralCatalog>The Extensible Markup Language (XML), with its ability to define formal
                structural and semantic definitions for metadata and information models, is the key
                enabling technology for information services and document-centric business models
                that use the Internet and its family of protocols. This course introduces XML
                syntax, transformations, schema languages and the querying of XML databases. It
                balances conceptual topics with practical skills for designing, implementing, and
                handling conceptual models as XML schemas.</GeneralCatalog>
            <DepartmentDescription>Three hours of lecture. The Extensible Markup Language (XML),
                with its ability to define formal structural and semantic definitions for metadata
                and information models, is the key enabling technology for information services and
                document-centric business models that use the Internet and its family of protocols.
                This course introduces XML syntax, transformations, schema languages, and the
                querying of XML databases. It balances conceptual topics with practical skills for
                designing, implementing, and handling conceptual models as XML
                schemas.</DepartmentDescription>
        </CourseDescriptions>
        <Department>School of Information</Department>
                <Units>3</Units>
        <CourseFormat>
            <CourseFormatOption>
                <CourseHours>3</CourseHours>
                <CourseFormatType>Lecture</CourseFormatType>
                <CourseFormatFrequency>Weekly</CourseFormatFrequency>
            </CourseFormatOption>
        </CourseFormat>
        <CourseStartDate>2013-08-27</CourseStartDate>
        <CourseEndDate>2013-12-20</CourseEndDate>
        <Sections>
            <Section>
                <SectionTitle>Lecture</SectionTitle>
                <SectionCode>Lecture01</SectionCode>
                <SectionShortCode>LEC 01</SectionShortCode>
                <SectionCCN>41613</SectionCCN>
                <SectionType>Lecture</SectionType>
                <SectionInstructor>Erik Wilde</SectionInstructor>
                <SectionSchedule>
                    <SectionScheduleEntry>
                        <ScheduledTime>
                            <Day>Monday</Day>
                            <Day>Wednesday</Day>
                            <StartTime>14:00</StartTime>
                            <EndTime>15:30</EndTime>
                            <Frequency>Weekly</Frequency>
                        </ScheduledTime>
                        <ScheduledLocation>
                            <Building>South Hall</Building>
                            <Room>202</Room>
                        </ScheduledLocation>
                    </SectionScheduleEntry>
              </SectionSchedule>
            </Section>
        </Sections>
        <Instructors>
            <Instructor>
                <InstructorName>Erik Wilde</InstructorName>
                <InstructorType>Professor</InstructorType>
                <InstructorEmail>dret@ischool.berkeley.edu</InstructorEmail>
                <InstructorLink></InstructorLink>
            </Instructor>
            <Instructor>
                <InstructorName>Remond Yee</InstructorName>
                <InstructorType>Guest Professor</InstructorType>
                <InstructorEmail></InstructorEmail>
                <InstructorLink></InstructorLink>
            </Instructor>
            <Instructor>
                <InstructorName>Eric C. Kansa</InstructorName>
                <InstructorType>Guest Speaker</InstructorType>
                <InstructorEmail>Some Company</InstructorEmail>
                <InstructorLink></InstructorLink>
            </Instructor>
        </Instructors>
        <!-- What about flex units?-->
        <Grading>
            <CreditOptions>Rigid</CreditOptions>
            
            <GradingOptions>
                <GradingOption>Graded</GradingOption>
                <GradingOption>Pass Fail</GradingOption>
            </GradingOptions>
           
            <GradingBreakdown>
                <GradingElement>
                    <GradingElementTitle>Assignments</GradingElementTitle>
                    <!-- free text -->
                    <GradingElementType>Assignment</GradingElementType>
                   
                    <GradingElementWeight>0.25</GradingElementWeight>
                </GradingElement>
                <GradingElement>
                    <GradingElementTitle>Final Project Report</GradingElementTitle>
                    <GradingElementType>Project</GradingElementType>
                    <GradingElementWeight>0.25</GradingElementWeight>
                </GradingElement>
                <GradingElement>
                    <GradingElementTitle>Final Exam (Oral)</GradingElementTitle>
                    <GradingElementType>Final Exam</GradingElementType>
                    <GradingElementWeight>0.5</GradingElementWeight>
                </GradingElement>
            </GradingBreakdown>
        </Grading>
        <Milestones>
            <Milestone>
                <MilestoneTitle>Final Exam</MilestoneTitle>
                <MilestoneType>Final Exam</MilestoneType>
                <!-- Project, Report, Essay, Midterm, Final Exam -->
                <MilestoneDueDate>2013-12-17</MilestoneDueDate>
                <MilestoneDueTime>10:00</MilestoneDueTime>
                <MilestoneDueLocation>Southall 202</MilestoneDueLocation>
            </Milestone>
            <Milestone>
                <MilestoneTitle>Mid Term Exam</MilestoneTitle>
                <MilestoneType>Mid TermExam</MilestoneType>
                <!-- Project, Report, Essay, Midterm, Final Exam -->
                <MilestoneDueDate>2013-11-05</MilestoneDueDate>
                <MilestoneDueTime>09:00</MilestoneDueTime>
                <MilestoneDueLocation>Southall 202</MilestoneDueLocation>
            </Milestone>
        </Milestones>
        <ClassPerformance>
            <Grades>
                <StudentGrades>
                    <StudentGrade/>
                    <!-- A+ ... F-->
                </StudentGrades>
                <ClassAverage/>
            </Grades>
            <InstructorEvaluation>
                <!-- ADD MORE DETAILS HERE IF NECCESSARY -->
            </InstructorEvaluation>
        </ClassPerformance>
        <PreviousCourseCCN>40000</PreviousCourseCCN>
        <FinalExamGroup>None</FinalExamGroup>
        <!-- What is this?-->
        <Restrictions>
            <!-- need a list of restrictions-->
            <Restriction>By Category</Restriction>
        </Restrictions>
        <Notes/>
        <Prerequisites>
        </Prerequisites>
        <EquivilantCourses>
            <!-- links to any equivlant courses in the current semester -->
            <EquivalentCourseCCN/>
        </EquivilantCourses>
        <CourseEntryStatus>
            <CreatedOn>2013-03-08</CreatedOn>
            <CreatedBy>UNKNOWN</CreatedBy>
            <ModifiedOn/>
            <ModifiedBy/>
        </CourseEntryStatus>
        <Enrolment>
            <EnrolmentStatus>
                <EnrolmentUpdate>
                    <EnrolmentUpdatedOn>2013-10-09</EnrolmentUpdatedOn>
                    <Limit>35</Limit>
                    <Enrolled>17</Enrolled>
                    <Waitlist>0</Waitlist>
                    <AvailableSeats>18</AvailableSeats>
                </EnrolmentUpdate>
            </EnrolmentStatus>
        </Enrolment>
        <Fulfilments>
            <Fulfilment>
                <Degree>MIMS</Degree>
                <Department>School of Information</Department>
                <Requirement>Technology</Requirement>
                <FullfillmentType>Major<!--Minor, major...etc--></FullfillmentType>
            </Fulfilment>
        </Fulfilments>
    </Course>
    <Course>
        <UID>2</UID>
        <CourseCCN>41578</CourseCCN>
        <CourseSemester>Fall 2013</CourseSemester>
        <CourseCode>INFORMATION 202</CourseCode>
        <CourseShortCode>INFO 202</CourseShortCode>
        <CourseDepartmentalCode>i202</CourseDepartmentalCode>
        <CourseTitle>Information Organization and Retrieval</CourseTitle>
        <CourseAlternariveTitles>
            <AlternativeTitle>IOR</AlternativeTitle>
        </CourseAlternariveTitles>
        <CourseDescriptions>
            <GeneralCatalog>Organization, representation, and access to information. Categorization,
                indexing, and content analysis. Data structures. Design and maintenance of
                databases, indexes, classification schemes, and thesauri. Use of codes, formats, and
                standards. Analysis and evaluation of search and navigation
                techniques.</GeneralCatalog>
            <DepartmentDescription>Three hours of lecture per week. This course introduces the
                intellectual foundations of information organization and retrieval: conceptual
                modeling, semantic representation, vocabulary and metadata design, classification,
                and standardization, as well as information organization and retrieval practices,
                technology, and applications, including computational processes for analyzing
                information in both textual and non-textual formats. Students will learn how
